services:
  - type: web
    name: nexxauth
    env: node
    buildCommand: npm install && vite build --config vite.static.config.ts
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: nexxauth-db
          property: connectionString
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
      - key: VITE_FIREBASE_APP_ID
        sync: false

databases:
  - name: nexxauth-db
    databaseName: nexxauth
    user: nexxauth